// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Bcrypt = require("bcrypt");

function genSync($staropt$star, _) {
  return Bcrypt.genSaltSync($staropt$star ? $staropt$star[0] : 10);
}

function gen($staropt$star, _) {
  return Bcrypt.genSalt($staropt$star ? $staropt$star[0] : 10);
}

function compare(a, b) {
  return Bcrypt.compare(a, b).then((function (x) {
    return Promise.resolve(+x);
  }));
}

function hashAndSaltSync($staropt$star, data) {
  var rounds = $staropt$star ? $staropt$star[0] : 10;
  return Bcrypt.hashSync(data, rounds);
}

function hashAndSalt($staropt$star, data) {
  var rounds = $staropt$star ? $staropt$star[0] : 10;
  return Bcrypt.hash(data, rounds);
}

function Salt_000(prim) {
  return prim;
}

var Salt = [
  Salt_000,
  genSync,
  gen
];

function Hash_000(prim) {
  return prim;
}

function Hash_001(prim) {
  return Bcrypt.getRounds(prim);
}

function Hash_002(prim, prim$1) {
  return Bcrypt.hashSync(prim, prim$1);
}

function Hash_003(prim, prim$1) {
  return Bcrypt.hash(prim, prim$1);
}

function Hash_004(prim, prim$1) {
  return +Bcrypt.compareSync(prim, prim$1);
}

var Hash = [
  Hash_000,
  Hash_001,
  Hash_002,
  Hash_003,
  Hash_004,
  compare
];

exports.Salt = Salt;
exports.Hash = Hash;
exports.hashAndSaltSync = hashAndSaltSync;
exports.hashAndSalt = hashAndSalt;
/* bcrypt Not a pure module */
